# Site wide configuration

title:            Bob Kopp
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Bob Kopp
  avatar: bio-photo.jpg
  bio: "Climate scientist, Earth historian, geobiologist, and energy policy wonk, at <a href=\"http://www.rutgers.edu/\">Rutgers University</a>'s <a href=\"http://eps.rutgers.edu/\">Dept. of Earth & Planetary Sciences<a> and <a href=\"http://rei.rutgers.edu/\">Rutgers Energy Institute</a>."
  fullbio: /about/
  contact-page: /contact/
  cv: http://dl.dropbox.com/u/9892014/vitae.pdf
  email: robert-dot-kopp-at-rutgers-dot-edu
  disqus-shortname: 
  twitter: bobkopp
  facebook: #username
  orcid: 0000-0003-4016-9428
  google:
    scholar: ceifbhUAAAAJ
    plus: #username
    analytics: UA-10543328-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: bobkopp
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
